// Generated by scripts/generate-catalog.mjs. Do not edit.
export const catalog = [
  {
    "tag": "fluid-accordion",
    "storyId": "components-navigation-accordion--default",
    "source": "packages/components/src/components/accordion/fluid-accordion.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-anchor-nav",
    "storyId": "components-navigation-anchor-nav--default",
    "source": "packages/components/src/components/anchor-nav/fluid-anchor-nav.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-animated-image",
    "storyId": "media-animated-image--default",
    "source": "packages/media/src/components/animated-image/fluid-animated-image.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-animation",
    "storyId": "components-utilities-animation--preset",
    "source": "packages/components/src/components/animation/fluid-animation.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-app-bar",
    "storyId": "components-navigation-app-bar--default",
    "source": "packages/components/src/components/app-bar/fluid-app-bar.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-aspect-ratio",
    "storyId": "components-layout-aspect-ratio--default",
    "source": "packages/components/src/components/aspect-ratio/fluid-aspect-ratio.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-audio",
    "storyId": "media-audio--default",
    "source": "packages/media/src/components/audio/fluid-audio.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-availability-editor",
    "storyId": "scheduler-availability-editor--default",
    "source": "packages/scheduler/src/components/availability-editor/fluid-availability-editor.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-avatar",
    "storyId": "components-content-avatar--initials",
    "source": "packages/components/src/components/avatar/fluid-avatar.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-avatar-group",
    "storyId": "components-content-avatar-group--default",
    "source": "packages/components/src/components/avatar-group/fluid-avatar-group.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-badge",
    "storyId": "components-content-badge--default",
    "source": "packages/components/src/components/badge/fluid-badge.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-banner",
    "storyId": "components-feedback-banner--default",
    "source": "packages/components/src/components/banner/fluid-banner.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-bar-chart",
    "storyId": "charts-gallery--bar",
    "source": "packages/charts/src/components/chart/fluid-charts.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-breadcrumb",
    "storyId": "components-navigation-breadcrumb--default",
    "source": "packages/components/src/components/breadcrumb/fluid-breadcrumb.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-breadcrumb-item",
    "storyId": "components-navigation-breadcrumb--default",
    "source": "packages/components/src/components/breadcrumb/fluid-breadcrumb.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-bubble-chart",
    "storyId": "charts-gallery--bubble",
    "source": "packages/charts/src/components/chart/fluid-charts.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-button",
    "storyId": "components-forms-button--primary",
    "source": "packages/components/src/components/button/fluid-button.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-button-group",
    "storyId": "components-forms-buttongroup--default",
    "source": "packages/components/src/components/button-group/fluid-button-group.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-calendar",
    "storyId": "components-forms-calendar--single",
    "source": "packages/components/src/components/calendar/fluid-calendar.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-callout",
    "storyId": "components-feedback-callout--default",
    "source": "packages/components/src/components/callout/fluid-callout.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-card",
    "storyId": "components-layout-card--default",
    "source": "packages/components/src/components/card/fluid-card.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-carousel",
    "storyId": "components-layout-carousel--default",
    "source": "packages/components/src/components/carousel/fluid-carousel.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-carousel-item",
    "storyId": "components-layout-carousel--default",
    "source": "packages/components/src/components/carousel/fluid-carousel.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-celebrate",
    "storyId": "animations-effects--declarative-auto",
    "source": "packages/animations/src/effects/effects.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-chart",
    "storyId": "charts-gallery--generic",
    "source": "packages/charts/src/components/chart/fluid-charts.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-checkbox",
    "storyId": "components-forms-checkbox--default",
    "source": "packages/components/src/components/checkbox/fluid-checkbox.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-code-block",
    "storyId": "components-content-codeblock--css",
    "source": "packages/components/src/components/code-block/fluid-code-block.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-col",
    "storyId": "components-layout-grid--spanning",
    "source": "packages/components/src/components/grid/fluid-grid.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-color-picker",
    "storyId": "components-forms-colorpicker--default",
    "source": "packages/components/src/components/color-picker/fluid-color-picker.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-column-mapper",
    "storyId": "parser-column-mapper--default",
    "source": "packages/parser/src/components/column-mapper/fluid-column-mapper.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-command-palette",
    "storyId": "components-navigation-command-palette--default",
    "source": "packages/components/src/components/command-palette/fluid-command-palette.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-comparison",
    "storyId": "components-content-comparison--default",
    "source": "packages/components/src/components/comparison/fluid-comparison.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-context-menu",
    "storyId": "components-navigation-context-menu--default",
    "source": "packages/components/src/components/context-menu/fluid-context-menu.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-copy-button",
    "storyId": "components-content-copybutton--default",
    "source": "packages/components/src/components/copy-button/fluid-copy-button.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-countdown",
    "storyId": "components-content-countdown--default",
    "source": "packages/components/src/components/countdown/fluid-countdown.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-date-picker",
    "storyId": "components-forms-date-picker--default",
    "source": "packages/components/src/components/date-picker/fluid-date-picker.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-date-range-picker",
    "storyId": "components-forms-date-range-picker--default",
    "source": "packages/components/src/components/date-range-picker/fluid-date-range-picker.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-description-item",
    "storyId": "components-content-description-list--default",
    "source": "packages/components/src/components/description-list/fluid-description-list.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-description-list",
    "storyId": "components-content-description-list--default",
    "source": "packages/components/src/components/description-list/fluid-description-list.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-details",
    "storyId": "components-navigation-accordion--default",
    "source": "packages/components/src/components/accordion/fluid-accordion.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-dialog",
    "storyId": "components-feedback-dialog--default",
    "source": "packages/components/src/components/dialog/fluid-dialog.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-divider",
    "storyId": "components-layout-divider--horizontal",
    "source": "packages/components/src/components/divider/fluid-divider.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-doughnut-chart",
    "storyId": "charts-gallery--doughnut",
    "source": "packages/charts/src/components/chart/fluid-charts.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-drawer",
    "storyId": "components-feedback-drawer--all-placements",
    "source": "packages/components/src/components/drawer/fluid-drawer.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-dropdown",
    "storyId": "components-navigation-dropdown--default",
    "source": "packages/components/src/components/dropdown/fluid-dropdown.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-dropdown-item",
    "storyId": "components-navigation-dropdown--default",
    "source": "packages/components/src/components/dropdown/fluid-dropdown.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-dropzone",
    "storyId": "components-forms-dropzone--default",
    "source": "packages/components/src/components/dropzone/fluid-dropzone.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-empty-state",
    "storyId": "components-feedback-empty-state--default",
    "source": "packages/components/src/components/empty-state/fluid-empty-state.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-event-calendar",
    "storyId": "calendar-event-calendar--default",
    "source": "packages/calendar/src/components/event-calendar/fluid-event-calendar.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-field",
    "storyId": "components-forms-field--default",
    "source": "packages/components/src/components/field/fluid-field.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-fieldset",
    "storyId": "components-forms-fieldset--default",
    "source": "packages/components/src/components/fieldset/fluid-fieldset.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-file-input",
    "storyId": "components-forms-fileinput--default",
    "source": "packages/components/src/components/file-input/fluid-file-input.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-file-parser",
    "storyId": "parser-file-parser--default",
    "source": "packages/parser/src/components/file-parser/fluid-file-parser.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-fold",
    "storyId": "components-layout-fold--folded",
    "source": "packages/components/src/components/fold/fluid-fold.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-form",
    "storyId": "components-forms-form--default",
    "source": "packages/components/src/components/form/fluid-form.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-format-bytes",
    "storyId": "components-utilities-bytes--default",
    "source": "packages/components/src/components/format-bytes/fluid-format-bytes.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-format-date",
    "storyId": "components-utilities-date--default",
    "source": "packages/components/src/components/format-date/fluid-format-date.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-format-number",
    "storyId": "components-utilities-number--decimal",
    "source": "packages/components/src/components/format-number/fluid-format-number.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-grid",
    "storyId": "components-layout-grid--intrinsic",
    "source": "packages/components/src/components/grid/fluid-grid.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-hero",
    "storyId": "components-layout-hero--default",
    "source": "packages/components/src/components/hero/fluid-hero.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-hotkey",
    "storyId": "components-utilities-hotkey--default",
    "source": "packages/components/src/components/hotkey/fluid-hotkey.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-icon",
    "storyId": "components-content-icon--default",
    "source": "packages/components/src/components/icon/fluid-icon.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-image",
    "storyId": "components-content-image--default",
    "source": "packages/components/src/components/image/fluid-image.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-include",
    "storyId": "components-content-include--default",
    "source": "packages/components/src/components/include/fluid-include.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-infinite-table",
    "storyId": "table-infinite-table--template-columns",
    "source": "packages/table/src/components/infinite-table/fluid-infinite-table.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-input",
    "storyId": "components-forms-input--default",
    "source": "packages/components/src/components/input/fluid-input.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-intersection-observer",
    "storyId": "components-utilities-intersection-observer--default",
    "source": "packages/components/src/components/intersection-observer/fluid-intersection-observer.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-kanban",
    "storyId": "kanban-board--default",
    "source": "packages/kanban/src/components/kanban/fluid-kanban.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-kbd",
    "storyId": "components-content-kbd--default",
    "source": "packages/components/src/components/kbd/fluid-kbd.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-lightbox",
    "storyId": "media-lightbox--default",
    "source": "packages/media/src/components/lightbox/fluid-lightbox.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-line-chart",
    "storyId": "charts-gallery--line",
    "source": "packages/charts/src/components/chart/fluid-charts.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-list",
    "storyId": "components-content-list--default",
    "source": "packages/components/src/components/list/fluid-list.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-list-item",
    "storyId": "components-content-list--default",
    "source": "packages/components/src/components/list/fluid-list.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-loading-overlay",
    "storyId": "components-feedback-loading-overlay--default",
    "source": "packages/components/src/components/loading-overlay/fluid-loading-overlay.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-map",
    "storyId": "map-map--default",
    "source": "packages/map/src/components/map/fluid-map.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-markdown",
    "storyId": "expansion-markdown--default",
    "source": "packages/markdown/src/fluid-markdown.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-masked-input",
    "storyId": "components-forms-masked-input--default",
    "source": "packages/components/src/components/masked-input/fluid-masked-input.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-menu",
    "storyId": "components-navigation-menu--default",
    "source": "packages/components/src/components/menu/fluid-menu.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-menu-item",
    "storyId": "components-navigation-menu--default",
    "source": "packages/components/src/components/menu/fluid-menu.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-menu-label",
    "storyId": "components-navigation-menu--with-labels",
    "source": "packages/components/src/components/menu/fluid-menu.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-meter",
    "storyId": "components-feedback-meter--default",
    "source": "packages/components/src/components/meter/fluid-meter.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-mosaic",
    "storyId": "components-layout-mosaic--default",
    "source": "packages/components/src/components/mosaic/fluid-mosaic.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-mosaic-item",
    "storyId": "components-layout-mosaic--default",
    "source": "packages/components/src/components/mosaic/fluid-mosaic.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-mutation-observer",
    "storyId": "components-utilities-mutation-observer--default",
    "source": "packages/components/src/components/mutation-observer/fluid-mutation-observer.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-nav-item",
    "storyId": "components-navigation-nav-list--default",
    "source": "packages/components/src/components/nav-list/fluid-nav-list.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-nav-list",
    "storyId": "components-navigation-nav-list--default",
    "source": "packages/components/src/components/nav-list/fluid-nav-list.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-node-graph",
    "storyId": "node-graph-editor--editor",
    "source": "packages/node-graph/src/components/node-graph/fluid-node-graph.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-number-input",
    "storyId": "components-forms-numberinput--default",
    "source": "packages/components/src/components/number-input/fluid-number-input.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-option",
    "storyId": "components-forms-select--default",
    "source": "packages/components/src/components/select/fluid-select.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-otp",
    "storyId": "components-forms-otp-input--default",
    "source": "packages/components/src/components/otp/fluid-otp.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-page",
    "storyId": "components-layout-page--default",
    "source": "packages/components/src/components/page/fluid-page.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-pagination",
    "storyId": "components-navigation-pagination--default",
    "source": "packages/components/src/components/pagination/fluid-pagination.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-pie-chart",
    "storyId": "charts-gallery--pie",
    "source": "packages/charts/src/components/chart/fluid-charts.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-polar-area-chart",
    "storyId": "charts-gallery--polar-area",
    "source": "packages/charts/src/components/chart/fluid-charts.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-popconfirm",
    "storyId": "components-feedback-popconfirm--default",
    "source": "packages/components/src/components/popconfirm/fluid-popconfirm.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-popover",
    "storyId": "components-navigation-popover--default",
    "source": "packages/components/src/components/popover/fluid-popover.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-popup",
    "storyId": "components-navigation-popup--default",
    "source": "packages/components/src/components/popup/fluid-popup.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-pricing-table",
    "storyId": "components-content-pricing-table--default",
    "source": "packages/components/src/components/pricing-table/fluid-pricing-table.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-pricing-tier",
    "storyId": "components-content-pricing-table--default",
    "source": "packages/components/src/components/pricing-table/fluid-pricing-table.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-progress-bar",
    "storyId": "components-feedback-progressbar--default",
    "source": "packages/components/src/components/progress-bar/fluid-progress-bar.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-progress-ring",
    "storyId": "components-feedback-progressring--default",
    "source": "packages/components/src/components/progress-ring/fluid-progress-ring.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-qr-code",
    "storyId": "qr-qr-code--default",
    "source": "packages/qr/src/fluid-qr-code.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-radar-chart",
    "storyId": "charts-gallery--radar",
    "source": "packages/charts/src/components/chart/fluid-charts.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-radio",
    "storyId": "components-forms-radio--vertical",
    "source": "packages/components/src/components/radio/fluid-radio.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-radio-group",
    "storyId": "components-forms-radio--vertical",
    "source": "packages/components/src/components/radio/fluid-radio.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-range-slider",
    "storyId": "components-forms-range-slider--default",
    "source": "packages/components/src/components/range-slider/fluid-range-slider.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-rating",
    "storyId": "components-forms-rating--default",
    "source": "packages/components/src/components/rating/fluid-rating.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-relative-time",
    "storyId": "components-utilities-relative-time--default",
    "source": "packages/components/src/components/relative-time/fluid-relative-time.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-resize-observer",
    "storyId": "components-utilities-resize-observer--default",
    "source": "packages/components/src/components/resize-observer/fluid-resize-observer.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-result",
    "storyId": "components-feedback-result--default",
    "source": "packages/components/src/components/result/fluid-result.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-rich-text-editor",
    "storyId": "editor-rich-text-editor--default",
    "source": "packages/editor/src/components/rich-text-editor/fluid-rich-text-editor.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-scatter-chart",
    "storyId": "charts-gallery--scatter",
    "source": "packages/charts/src/components/chart/fluid-charts.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-scheduler",
    "storyId": "scheduler-scheduler--vet-clinic",
    "source": "packages/scheduler/src/components/scheduler/fluid-scheduler.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-scroller",
    "storyId": "components-layout-scroller--horizontal",
    "source": "packages/components/src/components/scroller/fluid-scroller.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-segment",
    "storyId": "components-navigation-segmentedcontrol--default",
    "source": "packages/components/src/components/segmented-control/fluid-segmented-control.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-segmented-control",
    "storyId": "components-navigation-segmentedcontrol--default",
    "source": "packages/components/src/components/segmented-control/fluid-segmented-control.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-select",
    "storyId": "components-forms-select--default",
    "source": "packages/components/src/components/select/fluid-select.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-sidebar",
    "storyId": "components-navigation-sidebar--default",
    "source": "packages/components/src/components/sidebar/fluid-sidebar.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-signature-pad",
    "storyId": "components-forms-signature-pad--default",
    "source": "packages/components/src/components/signature-pad/fluid-signature-pad.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-skeleton",
    "storyId": "components-feedback-skeleton--default",
    "source": "packages/components/src/components/skeleton/fluid-skeleton.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-slider",
    "storyId": "components-forms-slider--default",
    "source": "packages/components/src/components/slider/fluid-slider.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-sparkline",
    "storyId": "charts-gallery--sparkline",
    "source": "packages/charts/src/components/chart/fluid-charts.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-speed-dial",
    "storyId": "components-navigation-speed-dial--default",
    "source": "packages/components/src/components/speed-dial/fluid-speed-dial.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-spinner",
    "storyId": "components-feedback-spinner--default",
    "source": "packages/components/src/components/spinner/fluid-spinner.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-split-panel",
    "storyId": "components-layout-split-panel--default",
    "source": "packages/components/src/components/split-panel/fluid-split-panel.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-stack",
    "storyId": "components-layout-stack--vertical",
    "source": "packages/components/src/components/stack/fluid-stack.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-stat",
    "storyId": "components-content-stat--default",
    "source": "packages/components/src/components/stat/fluid-stat.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-step",
    "storyId": "components-navigation-steps--horizontal",
    "source": "packages/components/src/components/steps/fluid-steps.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-steps",
    "storyId": "components-navigation-steps--horizontal",
    "source": "packages/components/src/components/steps/fluid-steps.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-switch",
    "storyId": "components-forms-switch--default",
    "source": "packages/components/src/components/switch/fluid-switch.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-tab",
    "storyId": "components-navigation-tabs--default",
    "source": "packages/components/src/components/tabs/fluid-tabs.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-tab-panel",
    "storyId": "components-navigation-tabs--default",
    "source": "packages/components/src/components/tabs/fluid-tabs.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-table",
    "storyId": "table-data-table--default",
    "source": "packages/table/src/components/table/fluid-table.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-tabs",
    "storyId": "components-navigation-tabs--default",
    "source": "packages/components/src/components/tabs/fluid-tabs.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-tag",
    "storyId": "components-content-tag--default",
    "source": "packages/components/src/components/tag/fluid-tag.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-tag-input",
    "storyId": "components-forms-tag-input--default",
    "source": "packages/components/src/components/tag-input/fluid-tag-input.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-textarea",
    "storyId": "components-forms-textarea--default",
    "source": "packages/components/src/components/textarea/fluid-textarea.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-theme-toggle",
    "storyId": "components-utilities-theme-toggle--default",
    "source": "packages/components/src/components/theme-toggle/fluid-theme-toggle.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-time-picker",
    "storyId": "components-forms-time-picker--default",
    "source": "packages/components/src/components/time-picker/fluid-time-picker.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-time-slots",
    "storyId": "scheduler-time-slots--default",
    "source": "packages/scheduler/src/components/time-slots/fluid-time-slots.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-timeline",
    "storyId": "components-content-timeline--default",
    "source": "packages/components/src/components/timeline/fluid-timeline.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-timeline-item",
    "storyId": "components-content-timeline--default",
    "source": "packages/components/src/components/timeline/fluid-timeline.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-toast",
    "storyId": "components-feedback-toast--default",
    "source": "packages/components/src/components/toast/fluid-toast.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-toast-item",
    "storyId": "components-feedback-toast--persistent",
    "source": "packages/components/src/components/toast/fluid-toast.stories.ts",
    "setupButtons": [
      "Show persistent toast"
    ]
  },
  {
    "tag": "fluid-toolbar",
    "storyId": "components-navigation-toolbar--default",
    "source": "packages/components/src/components/toolbar/fluid-toolbar.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-tooltip",
    "storyId": "components-feedback-tooltip--default",
    "source": "packages/components/src/components/tooltip/fluid-tooltip.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-tour",
    "storyId": "components-feedback-tour--default",
    "source": "packages/components/src/components/tour/fluid-tour.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-transfer",
    "storyId": "components-forms-transfer--default",
    "source": "packages/components/src/components/transfer/fluid-transfer.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-tree",
    "storyId": "components-navigation-tree--default",
    "source": "packages/components/src/components/tree/fluid-tree.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-tree-item",
    "storyId": "components-navigation-tree--default",
    "source": "packages/components/src/components/tree/fluid-tree.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-truncate",
    "storyId": "components-content-truncate--default",
    "source": "packages/components/src/components/truncate/fluid-truncate.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-typeahead",
    "storyId": "components-forms-typeahead--from-array",
    "source": "packages/components/src/components/typeahead/fluid-typeahead.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-video",
    "storyId": "media-video--default",
    "source": "packages/media/src/components/video/fluid-video.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-video-playlist",
    "storyId": "media-video-playlist--default",
    "source": "packages/media/src/components/video-playlist/fluid-video-playlist.stories.ts",
    "setupButtons": []
  },
  {
    "tag": "fluid-zoomable-frame",
    "storyId": "media-zoomableframe--default",
    "source": "packages/media/src/components/zoomable-frame/fluid-zoomable-frame.stories.ts",
    "setupButtons": []
  }
] as const;
