import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";

async function filesBelow(directory) {
  const entries = await readdir(directory, { withFileTypes: true }).catch((error) => {
    if (error.code === "ENOENT") return [];
    throw error;
  });
  const files = [];
  for (const entry of entries) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await filesBelow(path)));
    else files.push(path);
  }
  return files;
}

/** Compare exact generated bytes and file identities, not just an export count. */
export async function processGeneratedOutput(root, outputs, { check = false } = {}) {
  const problems = [];
  for (const [path, expected] of outputs) {
    if (!check) {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, expected, "utf8");
      continue;
    }
    const actual = await readFile(path, "utf8").catch((error) => {
      if (error.code === "ENOENT") return null;
      throw error;
    });
    if (actual !== expected)
      problems.push(`${actual === null ? "Missing" : "Stale"}: ${relative(root, path)}`);
  }
  // Never silently delete old generated files: a removed public subpath needs
  // an explicit compatibility decision.
  for (const directory of ["src/generated", "src/jsx"]) {
    for (const path of await filesBelow(join(root, directory))) {
      if (!outputs.has(path)) problems.push(`Unexpected generated file: ${relative(root, path)}`);
    }
  }
  if (problems.length)
    throw new Error(`React generated output is out of sync:\n${problems.join("\n")}`);
}
