import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { eventProp, nativeEventTypes } from "./event-props.mjs";
import { processGeneratedOutput } from "./generated-output.mjs";
import {
  checkManifestOutputs,
  expectedManifestOutputs,
  readRepositoryManifests
} from "../../../scripts/cem/canonical.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(here, "..");
const root = join(packageRoot, "..", "..");
const { records, registry } = await readRepositoryManifests(root);
// Refuse stale/tampered persisted metadata before generating consumer types.
await checkManifestOutputs(root, expectedManifestOutputs(records));
const generated = join(packageRoot, "src", "generated");
const check = process.argv.slice(2).includes("--check");
if (process.argv.slice(2).some((argument) => argument !== "--check")) {
  throw new Error("Usage: node scripts/generate.mjs [--check]");
}
const outputs = new Map();

const wrappers = [];
const jsxEntries = [];

for (const component of registry) {
  const { className, events } = component;
  const fileName = component.tag.slice("fluid-".length);
  const wrapperName = className;
  const eventLines = events.map(
    (event) => `    ${eventProp(event.name)}: "${event.name}" as EventName<${event.type.text}>`
  );
  const eventBlock = eventLines.length ? `,\n  events: {\n${eventLines.join(",\n")}\n  }` : "";
  const litReactImport = events.length
    ? `import { createComponent, type EventName } from "@lit/react";`
    : `import { createComponent } from "@lit/react";`;
  const eventImports = renderTypeImports(eventTypeImports(events));
  const output = `// Generated by scripts/generate.mjs. Do not edit.\nimport React from "react";\n${litReactImport}\nimport { ${className} as ${className}Element } from "${component.package}";\n${eventImports ? `${eventImports}\n` : ""}\nif (typeof customElements !== "undefined" && !customElements.get("${component.tag}")) {\n  customElements.define("${component.tag}", ${className}Element);\n}\n\nexport const ${wrapperName} = createComponent({\n  react: React,\n  tagName: "${component.tag}",\n  elementClass: ${className}Element${eventBlock}\n});\n`;
  outputs.set(join(generated, `${fileName}.ts`), output);
  wrappers.push(`export { ${wrapperName} } from "./generated/${fileName}.js";`);
  jsxEntries.push({ tag: component.tag, className, packageName: component.package, events });
}

outputs.set(
  join(packageRoot, "src", "index.ts"),
  `// Generated by scripts/generate.mjs. Do not edit.\n${wrappers.join("\n")}\n`
);

function eventTypeImports(events, imports = new Map()) {
  for (const event of events)
    for (const reference of event.type.references ?? []) {
      const names = imports.get(reference.package) ?? new Set();
      names.add(reference.name);
      imports.set(reference.package, names);
    }
  return imports;
}

function renderTypeImports(imports) {
  return [...imports]
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(
      ([packageName, names]) =>
        `import type { ${[...names].sort().join(", ")} } from "${packageName}";`
    )
    .join("\n");
}

function renderJsx(entries) {
  const packageImports = new Map();
  for (const entry of entries) {
    const names = packageImports.get(entry.packageName) ?? new Set();
    names.add(entry.className);
    packageImports.set(entry.packageName, names);
    eventTypeImports(entry.events, packageImports);
  }
  const imports = renderTypeImports(packageImports);
  const intrinsic = entries
    .map((entry) => {
      const eventTypes = nativeEventTypes(entry.events);
      return `      "${entry.tag}": React.DetailedHTMLProps<React.HTMLAttributes<${entry.className}>, ${entry.className}> & Partial<Omit<${entry.className}, keyof HTMLElement>> & { ${eventTypes} };`;
    })
    .join("\n");
  return `// Generated by scripts/generate.mjs. Do not edit.\nimport "react";\n${imports}\n\ndeclare module "react" {\n  namespace JSX {\n    interface IntrinsicElements {\n${intrinsic}\n    }\n  }\n}\n\nexport {};\n`;
}

const jsxDirectory = join(packageRoot, "src", "jsx");
const entriesByPackage = new Map();
for (const entry of jsxEntries) {
  const entries = entriesByPackage.get(entry.packageName) ?? [];
  entries.push(entry);
  entriesByPackage.set(entry.packageName, entries);
}
outputs.set(
  join(packageRoot, "src", "jsx.ts"),
  renderJsx(entriesByPackage.get("@fluid-ds/components") ?? [])
);
for (const [packageName, entries] of entriesByPackage) {
  outputs.set(join(jsxDirectory, `${packageName.split("/").at(-1)}.ts`), renderJsx(entries));
}

await processGeneratedOutput(packageRoot, outputs, { check });
console.log(
  `${check ? "Verified exact output for" : "Generated"} ${jsxEntries.length} React wrappers from ${records.length} source-verified canonical CEMs.`
);
