// Generated by scripts/build-lucide.ts. Do not edit by hand.
import { registerIcon } from "../registry.js";
export const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><rect width="6" height="14" x="3" y="5" rx="2" /><rect width="6" height="10" x="15" y="7" rx="2" /><path d="M3 2v20" /><path d="M21 2v20" /></svg>`;
registerIcon("align-horizontal-space-between", svg);
export default svg;
