// Generated by scripts/build-lucide.ts. Do not edit by hand.
import { registerIcon } from "../registry.js";
export const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="m3 8 4-4 4 4" /><path d="M7 4v16" /><rect x="15" y="4" width="4" height="6" ry="2" /><path d="M17 20v-6h-2" /><path d="M15 20h4" /></svg>`;
registerIcon("arrow-up-0-1", svg);
export default svg;
