// Generated by scripts/build-lucide.ts. Do not edit by hand.
import { registerIcon } from "../registry.js";
export const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="m4 6 3-3 3 3" /><path d="M7 17V3" /><path d="m14 6 3-3 3 3" /><path d="M17 17V3" /><path d="M4 21h16" /></svg>`;
registerIcon("arrows-up-from-line", svg);
export default svg;
