// Generated by scripts/build-lucide.ts. Do not edit by hand.
import { registerIcon } from "../registry.js";
export const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><rect width="7" height="13" x="3" y="8" rx="1" /><path d="m15 2-3 3-3-3" /><rect width="7" height="13" x="14" y="8" rx="1" /></svg>`;
registerIcon("between-vertical-start", svg);
export default svg;
