// Generated by scripts/build-lucide.ts. Do not edit by hand.
import { registerIcon } from "../registry.js";
export const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M11 14h1v4" /><path d="M16 2v4" /><path d="M3 10h18" /><path d="M8 2v4" /><rect x="3" y="4" width="18" height="18" rx="2" /></svg>`;
registerIcon("calendar-1", svg);
export default svg;
