// Generated by scripts/build-lucide.ts. Do not edit by hand.
import { registerIcon } from "../registry.js";
export const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M22 12A10 10 0 1 1 12 2" /><path d="M22 2 12 12" /><path d="M16 2h6v6" /></svg>`;
registerIcon("circle-arrow-out-up-right", svg);
export default svg;
