// Generated by scripts/build-lucide.ts. Do not edit by hand.
import { registerIcon } from "../registry.js";
export const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M11 12H3" /><path d="M16 6H3" /><path d="M16 18H3" /><path d="m19 10-4 4" /><path d="m15 10 4 4" /></svg>`;
registerIcon("list-x", svg);
export default svg;
