// Generated by scripts/build-lucide.ts. Do not edit by hand.
import { registerIcon } from "../registry.js";
export const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M5 16v2" /><path d="M19 16v2" /><rect width="20" height="8" x="2" y="8" rx="2" /><path d="M18 12h.01" /></svg>`;
registerIcon("radio-receiver", svg);
export default svg;
