// Generated by scripts/build-lucide.ts. Do not edit by hand.
import { registerIcon } from "../registry.js";
export const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M20.34 17.52a10 10 0 1 0-2.82 2.82" /><circle cx="19" cy="19" r="2" /><path d="m13.41 13.41 4.18 4.18" /><circle cx="12" cy="12" r="2" /></svg>`;
registerIcon("radius", svg);
export default svg;
