import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { selectFixtures } from "./fixture-selection.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..", "..");
const report = JSON.parse(await readFile(join(root, "quality/component-quality.json"), "utf8"));
const storybookIndex = JSON.parse(
  await readFile(join(root, "apps/storybook/storybook-static/index.json"), "utf8")
);
const output = join(here, "..", ".generated", "catalog.ts");
const entries = selectFixtures(report.components, storybookIndex);

await mkdir(dirname(output), { recursive: true });
await writeFile(
  output,
  `// Generated by scripts/generate-catalog.mjs. Do not edit.\nexport const catalog = ${JSON.stringify(entries, null, 2)} as const;\n`,
  "utf8"
);
console.log(`Generated ${entries.length} browser accessibility fixtures.`);
