// AUTO-GENERATED by scripts/generate-tests.mjs. Do not edit by hand.
// Source: packages/components/src/components/format-number/fluid-format-number.stories.ts
import { test, expect } from "@playwright/test";

test.describe("Format/Number", () => {
  test("Decimal", async ({ page }) => {
    await page.goto(`/iframe.html?id=format-number--decimal&viewMode=story`);
    // Wait for Storybook to render the story root and for fonts + custom
    // elements to finish upgrading. We screenshot the full viewport rather
    // than the root element because some stories render off-screen overlays
    // (dialog, drawer, toast) whose root has zero visible bounds.
    await page.waitForSelector("#storybook-root", { state: "attached" });
    await page.evaluate(() => document.fonts?.ready);
    // Detect Storybook's own error overlay early so the failure points at
    // the story instead of timing out on an empty root.
    const sbErr = await page.locator("#storybook-root-error-display, #error-message").first().textContent().catch(() => null);
    if (sbErr) {
      throw new Error(`Storybook failed to render story 'format-number--decimal': ${sbErr.trim()}`);
    }
    await page.waitForFunction(() => {
      const root = document.getElementById("storybook-root");
      return !!root && root.childElementCount > 0;
    }, { timeout: 5000 }).catch(() => {
      // Some stories (e.g. broken meta) leave the root empty. Fall through
      // and let the screenshot diff capture whatever's on screen, the
      // resulting baseline will show the Storybook error page, which makes
      // the issue obvious in review.
    });
    await page.waitForTimeout(150);
    await expect(page).toHaveScreenshot("decimal.png", {
      fullPage: false
    });
  });

  test("Currency", async ({ page }) => {
    await page.goto(`/iframe.html?id=format-number--currency&viewMode=story`);
    // Wait for Storybook to render the story root and for fonts + custom
    // elements to finish upgrading. We screenshot the full viewport rather
    // than the root element because some stories render off-screen overlays
    // (dialog, drawer, toast) whose root has zero visible bounds.
    await page.waitForSelector("#storybook-root", { state: "attached" });
    await page.evaluate(() => document.fonts?.ready);
    // Detect Storybook's own error overlay early so the failure points at
    // the story instead of timing out on an empty root.
    const sbErr = await page.locator("#storybook-root-error-display, #error-message").first().textContent().catch(() => null);
    if (sbErr) {
      throw new Error(`Storybook failed to render story 'format-number--currency': ${sbErr.trim()}`);
    }
    await page.waitForFunction(() => {
      const root = document.getElementById("storybook-root");
      return !!root && root.childElementCount > 0;
    }, { timeout: 5000 }).catch(() => {
      // Some stories (e.g. broken meta) leave the root empty. Fall through
      // and let the screenshot diff capture whatever's on screen, the
      // resulting baseline will show the Storybook error page, which makes
      // the issue obvious in review.
    });
    await page.waitForTimeout(150);
    await expect(page).toHaveScreenshot("currency.png", {
      fullPage: false
    });
  });

  test("Percent", async ({ page }) => {
    await page.goto(`/iframe.html?id=format-number--percent&viewMode=story`);
    // Wait for Storybook to render the story root and for fonts + custom
    // elements to finish upgrading. We screenshot the full viewport rather
    // than the root element because some stories render off-screen overlays
    // (dialog, drawer, toast) whose root has zero visible bounds.
    await page.waitForSelector("#storybook-root", { state: "attached" });
    await page.evaluate(() => document.fonts?.ready);
    // Detect Storybook's own error overlay early so the failure points at
    // the story instead of timing out on an empty root.
    const sbErr = await page.locator("#storybook-root-error-display, #error-message").first().textContent().catch(() => null);
    if (sbErr) {
      throw new Error(`Storybook failed to render story 'format-number--percent': ${sbErr.trim()}`);
    }
    await page.waitForFunction(() => {
      const root = document.getElementById("storybook-root");
      return !!root && root.childElementCount > 0;
    }, { timeout: 5000 }).catch(() => {
      // Some stories (e.g. broken meta) leave the root empty. Fall through
      // and let the screenshot diff capture whatever's on screen, the
      // resulting baseline will show the Storybook error page, which makes
      // the issue obvious in review.
    });
    await page.waitForTimeout(150);
    await expect(page).toHaveScreenshot("percent.png", {
      fullPage: false
    });
  });

  test("Unit", async ({ page }) => {
    await page.goto(`/iframe.html?id=format-number--unit&viewMode=story`);
    // Wait for Storybook to render the story root and for fonts + custom
    // elements to finish upgrading. We screenshot the full viewport rather
    // than the root element because some stories render off-screen overlays
    // (dialog, drawer, toast) whose root has zero visible bounds.
    await page.waitForSelector("#storybook-root", { state: "attached" });
    await page.evaluate(() => document.fonts?.ready);
    // Detect Storybook's own error overlay early so the failure points at
    // the story instead of timing out on an empty root.
    const sbErr = await page.locator("#storybook-root-error-display, #error-message").first().textContent().catch(() => null);
    if (sbErr) {
      throw new Error(`Storybook failed to render story 'format-number--unit': ${sbErr.trim()}`);
    }
    await page.waitForFunction(() => {
      const root = document.getElementById("storybook-root");
      return !!root && root.childElementCount > 0;
    }, { timeout: 5000 }).catch(() => {
      // Some stories (e.g. broken meta) leave the root empty. Fall through
      // and let the screenshot diff capture whatever's on screen, the
      // resulting baseline will show the Storybook error page, which makes
      // the issue obvious in review.
    });
    await page.waitForTimeout(150);
    await expect(page).toHaveScreenshot("unit.png", {
      fullPage: false
    });
  });
});
