// AUTO-GENERATED by scripts/generate-tests.mjs. Do not edit by hand.
// Source: packages/components/src/components/typeahead/fluid-typeahead.stories.ts
import { test, expect } from "@playwright/test";

test.describe("Components/Typeahead", () => {
  test("FromArray", async ({ page }) => {
    await page.goto(`/iframe.html?id=components-typeahead--from-array&viewMode=story`);
    // Wait for Storybook to render the story root and for fonts + custom
    // elements to finish upgrading. We screenshot the full viewport rather
    // than the root element because some stories render off-screen overlays
    // (dialog, drawer, toast) whose root has zero visible bounds.
    await page.waitForSelector("#storybook-root", { state: "attached" });
    await page.evaluate(() => document.fonts?.ready);
    // Detect Storybook's own error overlay early so the failure points at
    // the story instead of timing out on an empty root.
    const sbErr = await page.locator("#storybook-root-error-display, #error-message").first().textContent().catch(() => null);
    if (sbErr) {
      throw new Error(`Storybook failed to render story 'components-typeahead--from-array': ${sbErr.trim()}`);
    }
    await page.waitForFunction(() => {
      const root = document.getElementById("storybook-root");
      return !!root && root.childElementCount > 0;
    }, { timeout: 5000 }).catch(() => {
      // Some stories (e.g. broken meta) leave the root empty. Fall through
      // and let the screenshot diff capture whatever's on screen, the
      // resulting baseline will show the Storybook error page, which makes
      // the issue obvious in review.
    });
    await page.waitForTimeout(150);
    await expect(page).toHaveScreenshot("from-array.png", {
      fullPage: false
    });
  });

  test("FromJSONAttribute", async ({ page }) => {
    await page.goto(`/iframe.html?id=components-typeahead--from-json-attribute&viewMode=story`);
    // Wait for Storybook to render the story root and for fonts + custom
    // elements to finish upgrading. We screenshot the full viewport rather
    // than the root element because some stories render off-screen overlays
    // (dialog, drawer, toast) whose root has zero visible bounds.
    await page.waitForSelector("#storybook-root", { state: "attached" });
    await page.evaluate(() => document.fonts?.ready);
    // Detect Storybook's own error overlay early so the failure points at
    // the story instead of timing out on an empty root.
    const sbErr = await page.locator("#storybook-root-error-display, #error-message").first().textContent().catch(() => null);
    if (sbErr) {
      throw new Error(`Storybook failed to render story 'components-typeahead--from-json-attribute': ${sbErr.trim()}`);
    }
    await page.waitForFunction(() => {
      const root = document.getElementById("storybook-root");
      return !!root && root.childElementCount > 0;
    }, { timeout: 5000 }).catch(() => {
      // Some stories (e.g. broken meta) leave the root empty. Fall through
      // and let the screenshot diff capture whatever's on screen, the
      // resulting baseline will show the Storybook error page, which makes
      // the issue obvious in review.
    });
    await page.waitForTimeout(150);
    await expect(page).toHaveScreenshot("from-json-attribute.png", {
      fullPage: false
    });
  });

  test("AsyncLoader", async ({ page }) => {
    await page.goto(`/iframe.html?id=components-typeahead--async-loader&viewMode=story`);
    // Wait for Storybook to render the story root and for fonts + custom
    // elements to finish upgrading. We screenshot the full viewport rather
    // than the root element because some stories render off-screen overlays
    // (dialog, drawer, toast) whose root has zero visible bounds.
    await page.waitForSelector("#storybook-root", { state: "attached" });
    await page.evaluate(() => document.fonts?.ready);
    // Detect Storybook's own error overlay early so the failure points at
    // the story instead of timing out on an empty root.
    const sbErr = await page.locator("#storybook-root-error-display, #error-message").first().textContent().catch(() => null);
    if (sbErr) {
      throw new Error(`Storybook failed to render story 'components-typeahead--async-loader': ${sbErr.trim()}`);
    }
    await page.waitForFunction(() => {
      const root = document.getElementById("storybook-root");
      return !!root && root.childElementCount > 0;
    }, { timeout: 5000 }).catch(() => {
      // Some stories (e.g. broken meta) leave the root empty. Fall through
      // and let the screenshot diff capture whatever's on screen, the
      // resulting baseline will show the Storybook error page, which makes
      // the issue obvious in review.
    });
    await page.waitForTimeout(150);
    await expect(page).toHaveScreenshot("async-loader.png", {
      fullPage: false
    });
  });

  test("StrictSelection", async ({ page }) => {
    await page.goto(`/iframe.html?id=components-typeahead--strict-selection&viewMode=story`);
    // Wait for Storybook to render the story root and for fonts + custom
    // elements to finish upgrading. We screenshot the full viewport rather
    // than the root element because some stories render off-screen overlays
    // (dialog, drawer, toast) whose root has zero visible bounds.
    await page.waitForSelector("#storybook-root", { state: "attached" });
    await page.evaluate(() => document.fonts?.ready);
    // Detect Storybook's own error overlay early so the failure points at
    // the story instead of timing out on an empty root.
    const sbErr = await page.locator("#storybook-root-error-display, #error-message").first().textContent().catch(() => null);
    if (sbErr) {
      throw new Error(`Storybook failed to render story 'components-typeahead--strict-selection': ${sbErr.trim()}`);
    }
    await page.waitForFunction(() => {
      const root = document.getElementById("storybook-root");
      return !!root && root.childElementCount > 0;
    }, { timeout: 5000 }).catch(() => {
      // Some stories (e.g. broken meta) leave the root empty. Fall through
      // and let the screenshot diff capture whatever's on screen, the
      // resulting baseline will show the Storybook error page, which makes
      // the issue obvious in review.
    });
    await page.waitForTimeout(150);
    await expect(page).toHaveScreenshot("strict-selection.png", {
      fullPage: false
    });
  });
});
