// Generated by scripts/generate.mjs. Do not edit.
import "react";
import type { FluidCelebrate } from "@fluid-ds/animations";

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "fluid-celebrate": React.DetailedHTMLProps<React.HTMLAttributes<FluidCelebrate>, FluidCelebrate> & Partial<Omit<FluidCelebrate, keyof HTMLElement>> & { "onfluid-celebrate-end"?: (event: CustomEvent<unknown>) => void; };
    }
  }
}

export {};
