// Generated by scripts/generate.mjs. Do not edit.
import "react";
import type { FluidEventCalendar } from "@fluid-ds/calendar";

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "fluid-event-calendar": React.DetailedHTMLProps<React.HTMLAttributes<FluidEventCalendar>, FluidEventCalendar> & Partial<Omit<FluidEventCalendar, keyof HTMLElement>> & { "onfluid-day-click"?: (event: CustomEvent<unknown>) => void; "onfluid-event-click"?: (event: CustomEvent<unknown>) => void; "onfluid-month-change"?: (event: CustomEvent<unknown>) => void; };
    }
  }
}

export {};
