// Generated by scripts/generate.mjs. Do not edit.
import "react";
import type { FluidBarChart, FluidBubbleChart, FluidChart, FluidDoughnutChart, FluidLineChart, FluidPieChart, FluidPolarAreaChart, FluidRadarChart, FluidScatterChart, FluidSparkline } from "@fluid-ds/charts";

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "fluid-bar-chart": React.DetailedHTMLProps<React.HTMLAttributes<FluidBarChart>, FluidBarChart> & Partial<Omit<FluidBarChart, keyof HTMLElement>> & { "onfluid-legend-change"?: (event: CustomEvent<unknown>) => void; };
      "fluid-bubble-chart": React.DetailedHTMLProps<React.HTMLAttributes<FluidBubbleChart>, FluidBubbleChart> & Partial<Omit<FluidBubbleChart, keyof HTMLElement>> & { "onfluid-legend-change"?: (event: CustomEvent<unknown>) => void; };
      "fluid-chart": React.DetailedHTMLProps<React.HTMLAttributes<FluidChart>, FluidChart> & Partial<Omit<FluidChart, keyof HTMLElement>> & { "onfluid-legend-change"?: (event: CustomEvent<unknown>) => void; };
      "fluid-doughnut-chart": React.DetailedHTMLProps<React.HTMLAttributes<FluidDoughnutChart>, FluidDoughnutChart> & Partial<Omit<FluidDoughnutChart, keyof HTMLElement>> & { "onfluid-legend-change"?: (event: CustomEvent<unknown>) => void; };
      "fluid-line-chart": React.DetailedHTMLProps<React.HTMLAttributes<FluidLineChart>, FluidLineChart> & Partial<Omit<FluidLineChart, keyof HTMLElement>> & { "onfluid-legend-change"?: (event: CustomEvent<unknown>) => void; };
      "fluid-pie-chart": React.DetailedHTMLProps<React.HTMLAttributes<FluidPieChart>, FluidPieChart> & Partial<Omit<FluidPieChart, keyof HTMLElement>> & { "onfluid-legend-change"?: (event: CustomEvent<unknown>) => void; };
      "fluid-polar-area-chart": React.DetailedHTMLProps<React.HTMLAttributes<FluidPolarAreaChart>, FluidPolarAreaChart> & Partial<Omit<FluidPolarAreaChart, keyof HTMLElement>> & { "onfluid-legend-change"?: (event: CustomEvent<unknown>) => void; };
      "fluid-radar-chart": React.DetailedHTMLProps<React.HTMLAttributes<FluidRadarChart>, FluidRadarChart> & Partial<Omit<FluidRadarChart, keyof HTMLElement>> & { "onfluid-legend-change"?: (event: CustomEvent<unknown>) => void; };
      "fluid-scatter-chart": React.DetailedHTMLProps<React.HTMLAttributes<FluidScatterChart>, FluidScatterChart> & Partial<Omit<FluidScatterChart, keyof HTMLElement>> & { "onfluid-legend-change"?: (event: CustomEvent<unknown>) => void; };
      "fluid-sparkline": React.DetailedHTMLProps<React.HTMLAttributes<FluidSparkline>, FluidSparkline> & Partial<Omit<FluidSparkline, keyof HTMLElement>> & {  };
    }
  }
}

export {};
