// Generated by scripts/generate.mjs. Do not edit.
import "react";
import type { FluidRichTextEditor } from "@fluid-ds/editor";

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "fluid-rich-text-editor": React.DetailedHTMLProps<React.HTMLAttributes<FluidRichTextEditor>, FluidRichTextEditor> & Partial<Omit<FluidRichTextEditor, keyof HTMLElement>> & { "onfluid-change"?: (event: CustomEvent<unknown>) => void; };
    }
  }
}

export {};
