// Generated by scripts/generate.mjs. Do not edit.
import "react";
import type { FluidKanban } from "@fluid-ds/kanban";

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "fluid-kanban": React.DetailedHTMLProps<React.HTMLAttributes<FluidKanban>, FluidKanban> & Partial<Omit<FluidKanban, keyof HTMLElement>> & { "onfluid-move"?: (event: CustomEvent<unknown>) => void; };
    }
  }
}

export {};
