// Generated by scripts/generate.mjs. Do not edit.
import "react";
import type { FluidMap } from "@fluid-ds/map";

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "fluid-map": React.DetailedHTMLProps<React.HTMLAttributes<FluidMap>, FluidMap> & Partial<Omit<FluidMap, keyof HTMLElement>> & { "onfluid-marker-click"?: (event: CustomEvent<unknown>) => void; "onfluid-move"?: (event: CustomEvent<unknown>) => void; };
    }
  }
}

export {};
