// Generated by scripts/generate.mjs. Do not edit.
import "react";
import type { FluidMarkdown } from "@fluid-ds/markdown";

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "fluid-markdown": React.DetailedHTMLProps<React.HTMLAttributes<FluidMarkdown>, FluidMarkdown> & Partial<Omit<FluidMarkdown, keyof HTMLElement>> & { "onfluid-render"?: (event: CustomEvent<unknown>) => void; };
    }
  }
}

export {};
