// Generated by scripts/generate.mjs. Do not edit.
import "react";
import type { FluidAnimatedImage, FluidAudio, FluidLightbox, FluidVideo, FluidVideoPlaylist, FluidZoomableFrame } from "@fluid-ds/media";

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "fluid-animated-image": React.DetailedHTMLProps<React.HTMLAttributes<FluidAnimatedImage>, FluidAnimatedImage> & Partial<Omit<FluidAnimatedImage, keyof HTMLElement>> & { "onfluid-error"?: (event: CustomEvent<unknown>) => void; "onfluid-load"?: (event: CustomEvent<unknown>) => void; };
      "fluid-audio": React.DetailedHTMLProps<React.HTMLAttributes<FluidAudio>, FluidAudio> & Partial<Omit<FluidAudio, keyof HTMLElement>> & { "onfluid-ended"?: (event: CustomEvent<unknown>) => void; "onfluid-pause"?: (event: CustomEvent<unknown>) => void; "onfluid-play"?: (event: CustomEvent<unknown>) => void; };
      "fluid-lightbox": React.DetailedHTMLProps<React.HTMLAttributes<FluidLightbox>, FluidLightbox> & Partial<Omit<FluidLightbox, keyof HTMLElement>> & { "onfluid-change"?: (event: CustomEvent<unknown>) => void; "onfluid-close"?: (event: CustomEvent<unknown>) => void; "onfluid-open"?: (event: CustomEvent<unknown>) => void; };
      "fluid-video": React.DetailedHTMLProps<React.HTMLAttributes<FluidVideo>, FluidVideo> & Partial<Omit<FluidVideo, keyof HTMLElement>> & { "onfluid-ended"?: (event: CustomEvent<unknown>) => void; "onfluid-pause"?: (event: CustomEvent<unknown>) => void; "onfluid-play"?: (event: CustomEvent<unknown>) => void; };
      "fluid-video-playlist": React.DetailedHTMLProps<React.HTMLAttributes<FluidVideoPlaylist>, FluidVideoPlaylist> & Partial<Omit<FluidVideoPlaylist, keyof HTMLElement>> & { "onfluid-change"?: (event: CustomEvent<unknown>) => void; };
      "fluid-zoomable-frame": React.DetailedHTMLProps<React.HTMLAttributes<FluidZoomableFrame>, FluidZoomableFrame> & Partial<Omit<FluidZoomableFrame, keyof HTMLElement>> & { "onfluid-zoom"?: (event: CustomEvent<unknown>) => void; };
    }
  }
}

export {};
