// Generated by scripts/generate.mjs. Do not edit.
import "react";
import type { FluidNodeGraph } from "@fluid-ds/node-graph";

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "fluid-node-graph": React.DetailedHTMLProps<React.HTMLAttributes<FluidNodeGraph>, FluidNodeGraph> & Partial<Omit<FluidNodeGraph, keyof HTMLElement>> & { "onfluid-connect"?: (event: CustomEvent<unknown>) => void; "onfluid-edge-remove"?: (event: CustomEvent<unknown>) => void; "onfluid-node-drop"?: (event: CustomEvent<unknown>) => void; "onfluid-node-move"?: (event: CustomEvent<unknown>) => void; "onfluid-node-remove"?: (event: CustomEvent<unknown>) => void; "onfluid-selection-change"?: (event: CustomEvent<unknown>) => void; "onfluid-viewport-change"?: (event: CustomEvent<unknown>) => void; };
    }
  }
}

export {};
