// Generated by scripts/generate.mjs. Do not edit.
import "react";
import type { FluidColumnMapper, FluidFileParser } from "@fluid-ds/parser";

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "fluid-column-mapper": React.DetailedHTMLProps<React.HTMLAttributes<FluidColumnMapper>, FluidColumnMapper> & Partial<Omit<FluidColumnMapper, keyof HTMLElement>> & { "onfluid-mapping-change"?: (event: CustomEvent<unknown>) => void; };
      "fluid-file-parser": React.DetailedHTMLProps<React.HTMLAttributes<FluidFileParser>, FluidFileParser> & Partial<Omit<FluidFileParser, keyof HTMLElement>> & { "onfluid-file-loaded"?: (event: CustomEvent<unknown>) => void; "onfluid-parse"?: (event: CustomEvent<unknown>) => void; "onfluid-parse-error"?: (event: CustomEvent<unknown>) => void; };
    }
  }
}

export {};
