// Generated by scripts/generate.mjs. Do not edit.
import "react";
import type { FluidQrCode } from "@fluid-ds/qr";

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "fluid-qr-code": React.DetailedHTMLProps<React.HTMLAttributes<FluidQrCode>, FluidQrCode> & Partial<Omit<FluidQrCode, keyof HTMLElement>> & {  };
    }
  }
}

export {};
