// Generated by scripts/generate.mjs. Do not edit.
import "react";
import type { FluidRainbowBattery, FluidRainbowClock, FluidRainbowLandscape } from "@fluid-ds/rainbow";

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "fluid-rainbow-battery": React.DetailedHTMLProps<React.HTMLAttributes<FluidRainbowBattery>, FluidRainbowBattery> & Partial<Omit<FluidRainbowBattery, keyof HTMLElement>> & {  };
      "fluid-rainbow-clock": React.DetailedHTMLProps<React.HTMLAttributes<FluidRainbowClock>, FluidRainbowClock> & Partial<Omit<FluidRainbowClock, keyof HTMLElement>> & {  };
      "fluid-rainbow-landscape": React.DetailedHTMLProps<React.HTMLAttributes<FluidRainbowLandscape>, FluidRainbowLandscape> & Partial<Omit<FluidRainbowLandscape, keyof HTMLElement>> & {  };
    }
  }
}

export {};
