// Generated by scripts/generate.mjs. Do not edit.
import "react";
import type { FluidAvailabilityEditor, FluidScheduler, FluidTimeSlots } from "@fluid-ds/scheduler";

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "fluid-availability-editor": React.DetailedHTMLProps<React.HTMLAttributes<FluidAvailabilityEditor>, FluidAvailabilityEditor> & Partial<Omit<FluidAvailabilityEditor, keyof HTMLElement>> & { "onfluid-change"?: (event: CustomEvent<unknown>) => void; };
      "fluid-scheduler": React.DetailedHTMLProps<React.HTMLAttributes<FluidScheduler>, FluidScheduler> & Partial<Omit<FluidScheduler, keyof HTMLElement>> & { "onfluid-change"?: (event: CustomEvent<unknown>) => void; "onfluid-day-select"?: (event: CustomEvent<unknown>) => void; "onfluid-range-change"?: (event: CustomEvent<unknown>) => void; };
      "fluid-time-slots": React.DetailedHTMLProps<React.HTMLAttributes<FluidTimeSlots>, FluidTimeSlots> & Partial<Omit<FluidTimeSlots, keyof HTMLElement>> & { "onfluid-change"?: (event: CustomEvent<unknown>) => void; };
    }
  }
}

export {};
