// Generated by scripts/generate.mjs. Do not edit.
import "react";
import type { FluidInfiniteTable, FluidTable } from "@fluid-ds/table";

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "fluid-infinite-table": React.DetailedHTMLProps<React.HTMLAttributes<FluidInfiniteTable>, FluidInfiniteTable> & Partial<Omit<FluidInfiniteTable, keyof HTMLElement>> & { "onfluid-column-layout-change"?: (event: CustomEvent<unknown>) => void; "onfluid-load-more"?: (event: CustomEvent<unknown>) => void; "onfluid-row-click"?: (event: CustomEvent<unknown>) => void; "onfluid-sort"?: (event: CustomEvent<unknown>) => void; };
      "fluid-table": React.DetailedHTMLProps<React.HTMLAttributes<FluidTable>, FluidTable> & Partial<Omit<FluidTable, keyof HTMLElement>> & { "onfluid-selection-change"?: (event: CustomEvent<unknown>) => void; "onfluid-sort"?: (event: CustomEvent<unknown>) => void; };
    }
  }
}

export {};
