/**
 * Generates one TypeScript module per lucide icon under `src/lucide/`.
 *
 * Each file is a side-effect module: importing it registers the icon by name
 * with the registry. Consumers get fine-grained control:
 *
 *   import "@fluid-ds/icons/lucide/check";   // registers just `check`
 *   import "@fluid-ds/icons/lucide/x";       // registers just `x`
 *
 * `register-defaults.ts` imports a curated subset of these; `loadIcon(name)`
 * (in registry.ts) lazy-imports any of them on demand.
 *
 * Why generate instead of running this transformation at runtime?
 *   - One file per icon = optimal tree-shaking. Bundlers code-split each.
 *   - We can ship the package without a runtime dep on lucide-static.
 *   - The output is human-readable; diffs show exactly which icons changed
 *     when lucide-static is upgraded.
 *
 * Run via `pnpm --filter @fluid-ds/icons build:icons`.
 */
import { readdir, readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = dirname(HERE);
const ICONS_SRC = join(ROOT, "node_modules/lucide-static/icons");
const OUT_DIR = join(ROOT, "src/lucide");

/**
 * Normalize the SVG so it matches our existing icon convention:
 *  - Strip the leading license comment (lucide ships one per file)
 *  - Strip the class="lucide ..." attribute (a CSS-class hook tied to lucide,
 *    we don't want users picking it up)
 *  - Collapse whitespace so the runtime string is small
 *  - Add aria-hidden + focusable=false so consumers don't have to remember
 */
function normalize(svg: string): string {
  return svg
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/\sclass="[^"]*"/g, "")
    .replace(/>\s+</g, "><")
    .replace(/\s{2,}/g, " ")
    .replace(/<svg([^>]*)>/, (_m, attrs: string) => {
      const next = attrs.includes("aria-hidden")
        ? attrs
        : `${attrs.trimEnd()} aria-hidden="true" focusable="false"`;
      return `<svg${next}>`;
    })
    .trim();
}

/** Make a kebab-case name a valid identifier for documentation only. */
function nameFor(file: string): string {
  return file.replace(/\.svg$/, "");
}

async function main() {
  const files = (await readdir(ICONS_SRC)).filter((f) => f.endsWith(".svg")).sort();
  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  const all: { name: string; module: string }[] = [];
  for (const file of files) {
    const name = nameFor(file);
    const svg = normalize(await readFile(join(ICONS_SRC, file), "utf8"));
    // Escape backticks and ${...} so the SVG can live inside a template literal.
    const safe = svg.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
    const ts = `// Generated by scripts/build-lucide.ts. Do not edit by hand.\nimport { registerIcon } from "../registry.js";\nexport const svg = \`${safe}\`;\nregisterIcon(${JSON.stringify(name)}, svg);\nexport default svg;\n`;
    const outFile = join(OUT_DIR, `${name}.ts`);
    await writeFile(outFile, ts, "utf8");
    all.push({ name, module: name });
  }

  // Manifest used by the lazy loadIcon() loader so it can validate names and
  // produce useful errors for typos.
  const manifestLines = all.map((e) => `  ${JSON.stringify(e.name)}: () => import(${JSON.stringify(`./${e.module}.js`)})`);
  const manifest = `// Generated by scripts/build-lucide.ts. Do not edit by hand.\n/* eslint-disable */\nexport const LUCIDE_LOADERS: Record<string, () => Promise<unknown>> = {\n${manifestLines.join(",\n")}\n};\nexport const LUCIDE_NAMES: string[] = ${JSON.stringify(all.map((e) => e.name))};\n`;
  await writeFile(join(OUT_DIR, "_manifest.ts"), manifest, "utf8");

  console.log(`Generated ${all.length} lucide icon modules in ${OUT_DIR}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
