/** Generate the visual catalog from the built Storybook index and quality inventory. */
import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { selectVisualFixtures } from "./fixture-selection.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..", "..");
const app = join(here, "..");
const report = JSON.parse(await readFile(join(root, "quality/component-quality.json"), "utf8"));
const storybook = JSON.parse(
  await readFile(join(root, "apps/storybook/storybook-static/index.json"), "utf8")
);

const catalog = selectVisualFixtures(report.components, storybook);

const generated = join(app, ".generated");
const tests = join(app, "tests");
await mkdir(generated, { recursive: true });
await writeFile(
  join(generated, "catalog.ts"),
  `// Generated by scripts/generate-tests.mjs. Do not edit.\nexport const catalog = ${JSON.stringify(catalog, null, 2)} as const;\n`,
  "utf8"
);

// Tests are generated artifacts. Recreate the exact directory so deleted or
// renamed Storybook stories cannot leave executable orphan specs behind.
await rm(tests, { recursive: true, force: true });
await mkdir(tests, { recursive: true });
await copyFile(join(app, "templates/catalog.spec.ts"), join(tests, "catalog.spec.ts"));
await copyFile(
  join(app, "templates/fixture-contract.spec.ts"),
  join(tests, "fixture-contract.spec.ts")
);
await copyFile(
  join(app, "templates/fixture-presence.spec.ts"),
  join(tests, "fixture-presence.spec.ts")
);

console.log(
  `Generated ${catalog.length} visual stories for ${report.components.length} elements in ${relative(
    root,
    tests
  )}.`
);
