import { manifest } from "./theme-manifest.js";

/** Turn `{color.brand.600}` into `--fluid-color-brand-600`. */
function referenceToCssVar(value: string): string | null {
  const match = /^\{([^}]+)\}$/.exec(value.trim());
  if (!match || !match[1]) return null;
  const kebab = (s: string) => s.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();
  return `--fluid-${match[1].split(".").map(kebab).join("-")}`;
}

/**
 * Map of cssVar (e.g. "--fluid-color-brand-500") → user-supplied value.
 * Only contains tokens the user actually changed, the diff IS the state.
 */
type Overrides = Record<string, string>;

type Listener = (overrides: Overrides) => void;

/**
 * Tiny observable store. The playground's components subscribe; whenever the
 * user changes a token, we update the override map, apply it to the preview
 * element's inline style (so live preview is instant), and notify subscribers.
 */
/**
 * Pure state store. No DOM coupling, subscribers (e.g. the preview component)
 * apply overrides to their own elements. This avoids a class of bugs where a
 * DOM reference held by the store goes stale across HMR / re-render.
 */
class ThemeStore {
  private overrides: Overrides = {};
  private listeners = new Set<Listener>();

  /** Default value for a given cssVar, taken from the manifest. */
  defaults(cssVar: string): string | undefined {
    const found = manifest.primitives.find((t) => t.cssVar === cssVar);
    return found?.value;
  }

  /** Current value (override > default). */
  get(cssVar: string): string | undefined {
    return this.overrides[cssVar] ?? this.defaults(cssVar);
  }

  /** Read-only snapshot of the current diff. */
  diff(): Overrides {
    return { ...this.overrides };
  }

  /** Set an override. Empty string clears it (reverts to default). */
  set(cssVar: string, value: string): void {
    const def = this.defaults(cssVar);
    if (value === "" || value === def) {
      delete this.overrides[cssVar];
    } else {
      this.overrides[cssVar] = value;
    }
    this.notify();
  }

  /** Replace the whole override map (used by preset loading + URL restore). */
  replace(next: Overrides): void {
    this.overrides = {};
    for (const [cssVar, value] of Object.entries(next)) {
      const def = this.defaults(cssVar);
      if (value !== def) this.overrides[cssVar] = value;
    }
    this.notify();
  }

  /** Reset all overrides. */
  reset(): void {
    this.overrides = {};
    this.notify();
  }

  /** Subscribe to changes. Returns an unsubscribe function. */
  subscribe(listener: Listener): () => void {
    this.listeners.add(listener);
    listener(this.overrides);
    return () => this.listeners.delete(listener);
  }

  /**
   * Render the override map as a CSS string scoped under the given selector.
   * Used by the export panel; this is the file the user downloads.
   */
  toCSS(selector = '[data-fluid-brand="custom"]'): string {
    const keys = Object.keys(this.overrides).sort();
    if (!keys.length) {
      return `/* No customizations yet. Tweak some tokens. */`;
    }
    const lines = keys.map((k) => `  ${k}: ${this.overrides[k]};`);
    return `/* Generated by Fluid theme builder. */\n${selector} {\n${lines.join("\n")}\n}\n`;
  }

  /**
   * Apply the current override map as inline CSS variables on the given element.
   * Components that own the preview surface call this on each notify.
   *
   * Important CSS gotcha: when a semantic token like `--fluid-accent-base`
   * is declared at `:root` as `var(--fluid-color-brand-600)`, the spec says
   * its *computed value* is resolved at `:root` and that resolved hex is what
   * inherits down. If we override `--fluid-color-brand-600` lower in the tree,
   * descendants of that override see the new primitive but the SEMANTIC value
   * stays frozen to the originally-resolved hex.
   *
   * To make semantic tokens "live" under primitive overrides, we re-declare
   * every semantic token on the override element with its raw `var(...)`
   * reference. This forces re-resolution at the override scope so the new
   * primitive value flows through to the semantic, then to consumers.
   */
  applyTo(el: HTMLElement): void {
    // First clear any previously-set --fluid-* variables we no longer own.
    const styleAttr = el.getAttribute("style") ?? "";
    const surviving = styleAttr
      .split(";")
      .map((s) => s.trim())
      .filter((s) => {
        if (!s) return false;
        const colon = s.indexOf(":");
        if (colon < 0) return true;
        const prop = s.slice(0, colon).trim();
        return !prop.startsWith("--fluid-");
      });
    el.setAttribute("style", surviving.join("; "));

    // Re-declare every semantic token so it re-resolves at this scope.
    // We use the "light" scheme as the source of references; dark scheme
    // would need its own treatment if/when we expose multi-scheme overrides.
    for (const sem of manifest.semantics.light) {
      // If the user has overridden this semantic directly, use that.
      const override = this.overrides[sem.cssVar];
      if (override) {
        el.style.setProperty(sem.cssVar, override);
      } else if (sem.referencesPrimitive) {
        // Re-declare with the var() reference so the override propagates.
        const ref = referenceToCssVar(sem.value);
        if (ref) el.style.setProperty(sem.cssVar, `var(${ref})`);
      }
    }

    // Apply primitive overrides (and any non-semantic overrides not already set).
    for (const [cssVar, value] of Object.entries(this.overrides)) {
      el.style.setProperty(cssVar, value);
    }
  }

  /**
   * Apply ONLY the override diff inline on the given element, no semantic
   * re-declaration. Use this when the target IS the scheme-declaration scope
   * (the document root): there, a primitive override and the semantic that
   * references it live in the same scope, so the semantic re-resolves
   * automatically, AND we must NOT pin semantics to light-scheme refs (that
   * would clobber dark.css's [data-fluid-theme="dark"] values). The full
   * applyTo (with re-declaration) is for deeper preview scopes only.
   */
  applyOverridesTo(el: HTMLElement): void {
    const styleAttr = el.getAttribute("style") ?? "";
    const surviving = styleAttr
      .split(";")
      .map((s) => s.trim())
      .filter((s) => {
        if (!s) return false;
        const colon = s.indexOf(":");
        if (colon < 0) return true;
        return !s.slice(0, colon).trim().startsWith("--fluid-");
      });
    el.setAttribute("style", surviving.join("; "));
    for (const [cssVar, value] of Object.entries(this.overrides)) {
      el.style.setProperty(cssVar, value);
    }
  }

  private notify(): void {
    for (const listener of this.listeners) listener({ ...this.overrides });
  }
}

export const themeStore = new ThemeStore();
